### ISSUE TITLE
Error in analysing scintigraphy gastric volume data

### ISSUE THREAD

**Issue by MRWUR** [dmenne/gastempt#4]
Hi,
I am using this tool to conduct the half time of gastric emptying. However, while inserting the data in the the fitting gastric emptying curve tool a error occurs. The settings are Bayesian Stan fit, as suggested by the tool, because I have only 10 variables per record. Powexp (without overshoot) and no covariance. Then I selected nice powexp scintigraphy. I insirted the data with three columns; records, minutes and volume. Does somebody understand what probably went wrong?

**Comment by dmenne** [comment]
Hi, "an error occurs" is difficult to diagnose when I do not have the data. It would be best if you could zip the data you inserted, and insert it here. Or send the data per email to my address given in github.

**Comment by dmenne** [comment]
Since there was no response, I close the issue
