### ISSUE TITLE
Same t50 values for all records

### ISSUE THREAD

**Issue by esbenbolvig** [dmenne/gastempt#5]
Hi, 

I want to estimate gastric emtying half-time from MRI images after a liquid meal. The tool/analysis seems to work and converge with my own data and with the preset simulated data, however in the result table/spread sheet all values of the t50 and slope are the same for all subjects. 
I am running the tool through Docker desktop as described on the web page. 
Previous, when calculations could be performed online, this was not an issue. 
Btw, thanks for the nice application.

Best, Esben Mark

**Comment by dmenne** [comment]
Give it a try and please report back. I will only upload it to CRAN if there is no further problem

docker pull dmenne/gastempt

**Comment by dmenne** [comment]
Changes are in 0.7. on CRAN
